sudo: required
services:
  - docker


before_install:
  - docker build -t rayln_matrix/react-test -f ./client/Dockerfile.dev ./client

script:
  # Make sure the test won't hang
  - docker run -e CI=true rayln_matrix/react-test npm test

after_success:
  # after test, build production level
  - docker build -t rayln_matrix/multi-client ./client
  - docker build -t rayln_matrix/multi-nginx ./nginx
  - docker build -t rayln_matrix/multi-server ./server
  - docker build -t rayln_matrix/multi-worker ./worker
  #Use travis to login to docker CLi --> push image to docker hub
  # Env variable DOCKER_PASSWORD and DOCKER_ID should be set ar Travis
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push to docker hub
  - docker push rayln_matrix/multi-client
  - docker push rayln_matrix/multi-nginx
  - docker push rayln_matrix/multi-server
  - docker push rayln_matrix/multi-worker  
